# Generated by Django 2.1.1 on 2018-09-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.TextField(max_length=256)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField()),
                ('minutos', models.PositiveIntegerField()),
                ('segundos', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='t_completado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t_completado', to='Productividad.Tiempo'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='t_restante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t_restante', to='Productividad.Tiempo'),
        ),
    ]
