# Generated by Django 2.1.1 on 2018-09-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productividad', '0003_auto_20180917_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='h_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='h_inicio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='m_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='m_inicio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='s_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='s_inicio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
