# Generated by Django 2.1.1 on 2018-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productividad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='t_completado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='t_restante',
        ),
        migrations.AddField(
            model_name='tarea',
            name='horas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='minutos',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='segundos',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Tiempo',
        ),
    ]
