# Generated by Django 2.1.1 on 2018-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productividad', '0002_auto_20180916_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='horas',
            new_name='h_actual',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='minutos',
            new_name='h_inicio',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='segundos',
            new_name='m_actual',
        ),
        migrations.AddField(
            model_name='tarea',
            name='m_inicio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='s_actual',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='s_inicio',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
